### ISSUE TITLE
Azure ElasticSearch cluster resource

### ISSUE THREAD

**Issue by Dmitry1987** [crossplane/provider-azure#109]
### What problem are you facing?
No ElasticSearch resource for Azure

### How could Crossplane help solve your problem?
Support ElasticSearch resource for Azure 😁 

Would be great to have this supported!

**Comment by prasek** [comment]
@Dmitry1987 We couldn't find an Azure provided managed service for ElasticSearch. Are you looking for support for the https://www.elastic.co/azure managed service?

**Comment by Dmitry1987** [comment]
@prasek at the time I thought Azure Search (which is elasticsearch behind the scenes but the don't expose the vanilla API) is plain elasticsearch that I could use but after some time realized it's incompatible with native ES APIs that I need. 
We can close this one, thanks!
