### ISSUE TITLE
Extend SQLServerParameters for Azure SQL Postgres to support creating server from backup 

### ISSUE THREAD

**Issue by kornelione** [crossplane/provider-azure#209]
### What problem are you facing?
In case I need to provision a Azure SQL postgres server from an existing backup, I cannot do this with Crossplane.
It is however supported using Terraform:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_server#create_mode
### How could Crossplane help solve your problem?

Extend the CRD with a setting "create_mode" and "creation_source_id", and forward to azure cli when creating the server.
https://doc.crds.dev/github.com/crossplane/provider-azure/database.azure.crossplane.io/PostgreSQLServer/v1beta1

**Comment by negz** [comment]
Thanks for the feature request @kornelione! It seems like if we're lucky this will be a case of updating the hard coded value at https://github.com/crossplane/provider-azure/blob/b55e3a0/pkg/clients/database/postgresql.go#L85 such that it corresponds to a field in our API type definition that could be set to other values (e.g. `PointInTimeRestore` etc).
