### ISSUE TITLE
Extend SQLServerParameters for Azure SQL Postgres to support setting minimum tls version

### ISSUE THREAD

**Issue by kornelione** [crossplane/provider-azure#210]
### What problem are you facing?
I would like to configure all aspects of Azure SQL postgres servers using crossplane. 
To improve security on the azure sql postgres server, I would like to set minimum tls version to 1.2. This is supported using the azure portal, and also with Terraform. 
### How could Crossplane help solve your problem?
Extend the CRD for azure postgres server with a Sql server parameter like: ssl_minimal_tls_version_enforced = "TLS1_2"

I

**Comment by negz** [comment]
Thanks for the feature request @kornelione! It seems like this should be straightforward to add. I see that this corresponds to https://docs.microsoft.com/en-us/rest/api/postgresql/servers/create#minimaltlsversionenum, which [appears to be supported](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v42.3.0+incompatible/services/postgresql/mgmt/2017-12-01/postgresql?utm_source=gopls#ServerProperties) by the version of the SDK we're using.

I believe adding support for this field should involve adding it to our API type definition, then plumbing it up to https://github.com/crossplane/provider-azure/blob/b55e3a0/pkg/clients/database/postgresql.go#L80.
