### ISSUE TITLE
AKS nodepools

### ISSUE THREAD

**Issue by vfarcic** [crossplane/provider-azure#271]
### What problem are you facing?

There is no option to add node pools to the AKS cluster.

### How could Crossplane help solve your problem?

Add it to the API.

**Comment by jbw976** [comment]
Thanks for bringing this up @vfarcic, there's been more interest in this recently :)

Does #262 cover this request already for you?

**Comment by vfarcic** [comment]
My bad. I should have found that issue before creating a new one.
