### ISSUE TITLE
Add global poll interval flag

### ISSUE THREAD

**Issue by luebken** [crossplane/provider-azure#282]
### What problem are you facing?
I'd like to configure the polling interval of Azure. Similar to [GCP](https://github.com/crossplane/provider-gcp/pull/344) and [AWS](https://github.com/crossplane/provider-aws/pull/741)

### How could Crossplane help solve your problem?
Implement the polling interval as in the other providers. See also https://github.com/crossplane/crossplane-runtime/issues/253
Document the polling interval and other flags. See also https://github.com/crossplane/provider-aws/issues/808

**Comment by hasheddan** [comment]
@luebken assigning myself here -- I'll get this completed today 👍🏻
