### ISSUE TITLE
Updating external resource status in managed resources

### ISSUE THREAD

**Issue by soorena776** [crossplane/provider-azure#46]
### What problem are you facing?

The methods for updating managed resources for external resource observation currently have two issues:
1. The external status should be differentiated from the managed resource internal status, otherwise updating the status will erase the internal status. #39 addressed the overwriting problem, but still there needs to be a separate struct for external resources, as is the case in other stack repositories:
https://github.com/crossplaneio/stack-aws/blob/master/pkg/controller/network/vpc/controller.go#L138
https://github.com/crossplaneio/stack-gcp/blob/master/pkg/controller/compute/network.go#L133 

2. The logic for such updates should be in the `apis` not `pkg/clients`, since the former is versioned and the latter is not

**Comment by muvaf** [comment]
I don't really understand the problem as the links seem to be expired. Feel free to reopen if the issue still exists.
