### ISSUE TITLE
Azure not s3 wire compatible

### ISSUE THREAD

**Issue by lukeweber** [crossplane/provider-azure#97]
AzureBucket is intended to be an s3 compatible bucket abstraction Microsoft blob storage. However, blob storage isn't compatible with the S3 protocol. For local consumption we could run a s3 proxy as a sidecar, and for public consumption we could even run a proxy as a service.

[Blog about using minio as an s3 proxy to blob storage](https://open.microsoft.com/2017/11/09/s3cmd-amazon-s3-compatible-apps-azure-storage/)

**Comment by muvaf** [comment]
I don't think this is relevant anymore. We don't have a static strongly-typed Bucket CRD in core Crossplane now.
